version: '3.8'
volumes:
  mariadb_data:
networks:
  asterisk:
    driver: bridge
  softphone:
    driver: bridge
  softphone-api:
    driver: bridge
services:
  asterisk:
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "8088:8088" # Porta do HTTP
      - "3306:3306"
      - "5038:5038"
    volumes:
      - ./asterisk/configs:/etc/asterisk
      - mariadb_data:/var/lib/mysql
    networks:
      - asterisk
      - softphone-api
  softphone:
    build:
      context: ./softphone
      dockerfile: Dockerfile
    container_name: softphone
    volumes:
      - ./softphone/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - softphone
      - softphone-api
    depends_on:
      - softphone-api
  softphone-api:
    build: 
      context: ./softphone-api
      dockerfile: Dockerfile
    container_name: softphone-api
    networks:
      - softphone-api
      - asterisk
    depends_on:
      - asterisk
