version: '3.8'
volumes:
  mariadb_data:
networks:
  asterisk:
    driver: bridge
services:
  asterisk:
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "8088:8088" # Porta do HTTP
      - "3306:3306"
      - "5038:5038"
    volumes:
      - ./asterisk/configs:/etc/asterisk
      - mariadb_data:/var/lib/mysql
    networks:
      - asterisk
