version: '3.8'
volumes:
  mariadb_data:
networks:
  asterisk:
    driver: bridge
services:
  asterisk:
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "8088:8088" # Porta do HTTP
    volumes:
      - ./asterisk/configs:/etc/asterisk
      - ./mariadb/configs:/etc
    networks:
      - asterisk
    depends_on:
      - mariadb
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - asterisk
